export const Transak = {
  Events: {
    TRANSAK_WIDGET_CLOSE: 'TRANSAK_WIDGET_CLOSE',
    TRANSAK_WIDGET_INITIALISED: 'TRANSAK_WIDGET_INITIALISED',
    TRANSAK_WIDGET_OPEN: 'TRANSAK_WIDGET_OPEN',
    TRANSAK_ORDER_CREATED: 'TRANSAK_ORDER_CREATED',
    TRANSAK_ORDER_CANCELLED: 'TRANSAK_ORDER_CANCELLED',
    TRANSAK_ORDER_FAILED: 'TRANSAK_ORDER_FAILED',
    TRANSAK_ORDER_SUCCESSFUL: 'TRANSAK_ORDER_SUCCESSFUL',
  },

  OrderStatus: {
    onRamp: {
      AWAITING_PAYMENT_FROM_USER: 'AWAITING_PAYMENT_FROM_USER',
      PAYMENT_DONE_MARKED_BY_USER: 'PAYMENT_DONE_MARKED_BY_USER',
      PROCESSING: 'PROCESSING',
      PENDING_DELIVERY_FROM_TRANSAK: 'PENDING_DELIVERY_FROM_TRANSAK',
      ON_HOLD_PENDING_DELIVERY_FROM_TRANSAK:
        'ON_HOLD_PENDING_DELIVERY_FROM_TRANSAK',
      COMPLETED: 'COMPLETED',
      CANCELLED: 'CANCELLED',
      FAILED: 'FAILED',
      REFUNDED: 'REFUNDED',
      EXPIRED: 'EXPIRED',
    },
  },
};
